### PR TITLE
docs: update README with local installation instructions

### PR DESCRIPTION
**Pull request by PascalinDe**
related to https://github.com/c4dt/showcase/pull/289

### CODE REVIEW

**Comment by ineiti** [comment]
I would prefer to have that in its own `Dockerfile`, so that one can do

```
docker compose build
```

and it all does it automatically... Then we can do a `docker compose push` once, and the README.md is only

```
docker compose up --pull
```

**Review by ineiti — CHANGES_REQUESTED** [review]
I would prefer to have that in its own `Dockerfile`, so that one can do

```
docker compose build
```

and it all does it automatically... Then we can do a `docker compose push` once, and the README.md is only

```
docker compose up --pull
```

With docker-hub latest carfuffle around storing docker images of Open Source projects, I think ghcr.io would be a better place to store.

**Comment by PascalinDe** [comment]
> I would prefer to have that in its own `Dockerfile`, so that one can do
> 
> ```
> docker compose build
> ```
> 
> and it all does it automatically... Then we can do a `docker compose push` once, and the README.md is only
> 
> ```
> docker compose up --pull
> ```

yeah, I agree, having to install a handful of packages beforehand sort of defeats the purpose of having a Docker image... since you said we'd need a minimal README for today's Factory update I tried to document the current status quo there

> 
> With docker-hub latest carfuffle around storing docker images of Open Source projects, I think ghcr.io would be a better place to store.

yes, at least from a practical point of view there are no good arguments against it

**Review by ineiti — APPROVED** [review]

**Comment by ineiti** [comment]
Closing it in favor of #120

**Pull request closed without merging**
