### PR TITLE
Improvements to the dark mode

### PR DESCRIPTION
**Pull request by LucasTrg**
Fixes some font issues, and add better color management for stainless.

### CODE REVIEW

**Comment by cgrigis** [comment]
Seems `@c4dt/angular-components` was inadvertently removed from `package.json`?

**Comment by ineiti** [comment]
And needs 1-2 sentences in the description...

**Comment by cgrigis** [comment]
Looks good!  Perhaps the tutorial step headers are a bit "light" compared to the rest?

screenshot

**Comment by cgrigis** [comment]
Buttons in the dialog windows are also a bit flashy :-)

screenshot

**Pull request closed without merging**
